[build]
  publish = "site"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=86400, immutable"
